swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Todo List
  contact:
    email: ivonata13@gmail.com
host: localhost
basePath: /api/v1
schemes:
  - https
paths:
  /task:
    post:
      tags:
        - task
      summary: Add a new task
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Task object
          required: true
          schema:
            $ref: '#/definitions/AddTask'
      responses:
        201:
          description: Created
        400:
          description: Invalid format

  /task/{id}:
    put:
      tags:
        - task
      summary: Update task
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: task id
          required: true
          type: integer
        - in: body
          name: body
          description: Task object
          required: true
          schema:
            $ref: '#/definitions/UpdateTask'
      responses:
        204:
          description: No Content
        400:
          description: Invalid format
        404:
          description: Not Found

    delete:
      tags:
        - task
      summary: Delete task
      consumes:
        - application/json
      parameters:
        - name: id
          in: path
          description: task id
          required: true
          type: integer
      responses:
        204:
          description: NoContent
        400:
          description: Invalid format
        404:
          description: Not Found


  /tasks:
    get:
      tags:
        - tasks
      summary: Get task list
      produces:
        - application/json
      parameters:
        - name: completed
          in: query
          description: Task status
          required: true
          type: boolean
        - name: limit
          in: query
          description: Maximum number of records
          required: false
          type: integer
        - name: offset
          in: query
          description: Offset from start
          required: false
          type: integer
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/TaskItem'
        400:
          description: Invalid format


definitions:

  TaskItem:
    type: object
    required:
      - name
      - photoUrls
    properties:
      id:
        type: integer
      description:
        type: string

  AddTask:
    type: object
    required:
      - description
    properties:
      description:
        type: string

  UpdateTask:
    type: object
    required:
      - isCompleted
    properties:
      isCompleted:
        type: boolean
